Update pipeline.yml

diff --git a/.github/workflows/pipeline.yml b/.github/workflows/pipeline.yml
--- a/.github/workflows/pipeline.yml
+++ b/.github/workflows/pipeline.yml
@@ -25,36 +25,15 @@ jobs:
 
       - name: Build project
         run: dotnet build --configuration Release
-
-  test:
-    name: Test
-    runs-on: ubuntu-latest
-
-    needs: build
-
-    steps:
-      - name: Checkout repository
-        uses: actions/checkout@v3
-
-      - name: Cache .NET Core packages
-        uses: actions/cache@v3
-        with:
-          path: ~/.nuget/packages
-          key: ${{ runner.os }}-dotnet-${{ hashFiles('**/*.csproj') }}
-
-      - name: Restore dependencies
-        run: dotnet restore
-
-      - name: Build project
-        run: dotnet build --configuration Release
-
+        
       - name: Run tests
         run: dotnet test --logger trx --results-directory "TestResults"
-
-      - name: Upload test artifacts
-        uses: actions/upload-artifact@v3
+        
+      - name: Test Reports
+        uses: actions/upload-artifact@v2  # upload test results
+        if: success() || failure()        # run this step even if previous step failed
         with:
-          name: Test Results
-          path: TestResults
-        # Use always() to always run this step to publish test results when there are test failures
-        if: ${{ always() }}
+          name: test-results
+          path: TestResults/*.trx
+          reporter: dotnet-trx
+
